---
title: "Exploratory Data Analysis"
output: html_notebook
---

# Quantile Quantile Plots 
```{r}
library(UsingR)
library(rafalib)
x <- father.son$fheight
ps <- (seq(0,99) + 0.5 )/100
qs <- quantile(x, ps)
normalqs <- qnorm(ps, mean(x), popsd(x))
plot(normalqs,qs,xlab = "Normal percentiles", ylab = "Height percentiles")
abline(0,1)
```
```{r}
qqnorm(x)
qqline(x)
```
```{r}
n <- 1000
x <- rnorm(n)
qqnorm(x)
qqline(x)
```

```{r}
dfs <- c(3,6,12,30)
mypar(2,2)
for (df in dfs){
  x <- rt(1000,df)
  qqnorm(x,xlab = "t quantiles", main = paste0("d.f=",df),ylim=c(-6,6))
  qqline(x)
}
```

# Boxplots
```{r}
mypar(1,2)
hist(exec.pay)
qqnorm(exec.pay)
qqline(exec.pay)
```
```{r}
boxplot(exec.pay, ylab="10,000s of dollars", ylim=c(0,400))
```
# Scatterplots And Correlation
```{r}
library(UsingR)
data("father.son")
x = father.son$fheight
y = father.son$sheight
plot(x, y, xlab = "Father's height in inches", ylab = "Son's height in inches", main=paste("Correletion =", signif(cor(x,y),2)))
```
# Stratification 
Try to investigate whether a deviation in the father's height causes the same effect in son's height
```{r}
groups <- split(y, round(x))
boxplot(groups)
print(mean(y[ round(x) == 72]))
```
# Bi-variate Normal Distribution 
```{r}
groups <- split(y, round(x))
mypar(2,2)
for (i in c(5,8,11,14)){
  qqnorm(groups[[i]], main=paste0("X=", names(groups)[i],"strata"),
         ylim = range(y), xlim=c(-2.5,2.5))
  qqline(groups[[i]])
}
```
```{r}
x = (x - mean(x))/sd(x)
y = (y - mean(y))/sd(y)
means = tapply(y, round(x*4)/4,mean)
fatherheights = as.numeric(names(means))
mypar(1,1)
plot(fatherheights, means, ylab = "avg. of strata of son heights", ylim = range(fatherheights))
abline(0, cor(x,y))
```
```{r}
library("downloader")
filename <- "fig1.RData"
url <- "https://github.com/kbroman/Talk_Graphs/raw/master/R/fig1.RData"
if (!file.exists(filename)) download(url,filename)
load(filename)
```
```{r}
library(rafalib)
mypar()
dat <- list(Treatment=x,Control=y)
boxplot(dat,xlab="Group",ylab="Response",cex=0)
stripchart(dat,vertical=TRUE,method="jitter",pch=16,add=TRUE,col=1)
```
```{r}
library(downloader)
url <- "https://github.com/kbroman/Talk_Graphs/raw/master/R/fig3.RData"
filename <- "fig3.RData"
if (!file.exists(filename)) download(url, filename)
load(filename)
```
```{r}
library(rafalib)
mypar(1,2)
dat <- list(Treatment=x,Control=y)
boxplot(dat,xlab="Group",ylab="Response",cex=0)
stripchart(dat,vertical = TRUE,method="jitter",pch=16,add=TRUE,col=1)
boxplot(dat,xlab="Group",ylab="Response",log="y",cex=0)
stripchart(dat,vertical = TRUE,method="jitter",pch=16,add=TRUE,col=1)
```
```{r}
url <- "https://github.com/kbroman/Talk_Graphs/raw/master/R/fig4.RData"
filename <- "fig4.RData"
load(filename)
mypar(1,2)
plot(x,y,lwd=2,type="n")
fit <- lm(y~x)
abline(fit$coef,lwd=2)
b <- round(fit$coef,4)
text(78, 200, paste("y =", b[1], "+", b[2], "x"), adj=c(0,0.5))
rho <- round(cor(x,y),4)
text(78, 187, expression(paste(rho," = 0.8567")),adj=c(0,0.5))
plot(x,y,lwd=2)
fit <- lm(y~x)
abline(fit$coef, lwd=2)
```

